// Copyright 2023 Princess B33f Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package renderer

import (
	"reflect"

	highbase "github.com/pb33f/libopenapi/datamodel/high/base"
)

const (
	// Example is the field name used for a single mock example value.
	Example = "Example"

	// Examples is the field name used for named mock examples.
	Examples = "Examples"

	// Schema is the field name used for schema-based mock generation.
	Schema = "Schema"
)

const (
	// JSON renders mocks as JSON.
	JSON MockType = iota

	// YAML renders mocks as YAML.
	YAML

	// XML renders mocks as XML.
	XML
)

// MockType identifies the output format generated by MockGenerator.
type MockType int

// MockGenerator generates mocks for high-level mockable structs or *base.Schema pointers.
//
// Mockable structs can provide the following fields:
//   - Example: any type, this is the default example to use if no examples are present.
//   - Examples: *orderedmap.Map[string, *base.Example], this is a map of examples keyed by name.
//   - Schema: *base.SchemaProxy, this is the schema to use if no examples are present.
//
// Use NewMockGenerator or NewMockGeneratorWithDictionary to create a new mock generator.
type MockGenerator struct {
	renderer *SchemaRenderer
	mockType MockType
	pretty   bool
}

// NewMockGeneratorWithDictionary creates a MockGenerator using a custom dictionary file.
//
// The location of a text file with one word per line is expected.
func NewMockGeneratorWithDictionary(dictionaryLocation string, mockType MockType) *MockGenerator {
	_ = "STUB: not implemented"
	return nil
}

// NewMockGenerator creates a MockGenerator using the default dictionary.
//
// The default is located at /usr/share/dict/words on most systems. Windows users need to use
// NewMockGeneratorWithDictionary to specify a custom dictionary.
func NewMockGenerator(mockType MockType) *MockGenerator { _ = "STUB: not implemented"; return nil }

// SetPretty configures JSON mocks to render with indentation and newlines.
//
// JSON mocks render as a single line by default. This option affects only JSON; YAML is always rendered in YAML form.
func (mg *MockGenerator) SetPretty() {
	_ = "STUB: not implemented"

	// DisableRequiredCheck disables required-property filtering when rendering schema-based mocks.
	//
	// When disabled, all properties are rendered, not just required properties.
	return
}

func (mg *MockGenerator) DisableRequiredCheck() { _ = "STUB: not implemented"; return }

// SetUnresolvedRefHandler sets a callback that is invoked when a $ref cannot be resolved during mock rendering.
func (mg *MockGenerator) SetUnresolvedRefHandler(handler UnresolvedRefHandler) {
	_ = "STUB: not implemented"
	return
}

// SetMockGenerationOptions sets work and output budgets for generated mock values.
//
// Zero or negative option values are replaced with the package defaults.
func (mg *MockGenerator) SetMockGenerationOptions(options MockGenerationOptions) {
	_ = "STUB: not implemented"
	return
}

// SetSeed sets a specific seed for the random number generator used by this mock generator.
// This is useful for generating deterministic mocks for testing purposes.
func (mg *MockGenerator) SetSeed(seed int64) { _ = "STUB: not implemented"; return }

// extractSchema pulls the *base.Schema from a mockable struct or direct *base.Schema.
// Returns an error for unresolved refs or build failures while preserving existing error behavior.
func (mg *MockGenerator) extractSchema(mock any, v reflect.Value) (*highbase.Schema, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// renderForType dispatches rendering based on the configured mock type.
// For XML, it uses RenderXML with schema context; for JSON/YAML it uses renderMock.
func (mg *MockGenerator) renderForType(value any, schema *highbase.Schema) []byte {
	_ = "STUB: not implemented"
	return nil
}

// GenerateMock generates a mock for a high-level mockable struct or *base.Schema pointer.
//
// The name parameter is optional. When provided, GenerateMock attempts to select a matching named example. If name is
// empty, the first available example is used.
func (mg *MockGenerator) GenerateMock(mock any, name string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Extract schema before example selection so XML rendering can use schema metadata.

// Surface schema extraction errors only after example paths have had their chance.

func (mg *MockGenerator) renderMock(v any) []byte { _ = "STUB: not implemented"; return nil }

func (mg *MockGenerator) renderMockJSON(v any) []byte { _ = "STUB: not implemented"; return nil }

// determine the type, render properly.

// use json.Marshal for scalar types to produce valid JSON
// (e.g. strings get properly quoted: "bob" not bob)

func (mg *MockGenerator) renderMockYAML(v any) []byte {
	_ = "STUB: not implemented"

	// determine the type, render properly.
	return nil
}
